import fs from "node:fs/promises";
import path from "node:path";

import { CLOAK_KIT_ID, CloakKit, type CloakProfileCookie } from "../kits/cloak-kit";

import {
	defineBindings,
	type BpkgBindingResponseParser,
	type BpkgBindingPrepareContext,
	type BpkgTranspiledCommand,
} from "./define-bindings";

const YTDLP_DEFAULT_OUTPUT_DIR = "/root/Downloads";
const YTDLP_DEFAULT_OUTPUT_TEMPLATE = "%(title).200B [%(id)s].%(ext)s";
const YTDLP_COOKIE_JAR_PATH = "/root/.config/yt-dlp/cookies.txt";
const YTDLP_DESTINATION_MARKER = "__ISCAN_YTDLP_DEST__:";
const YTDLP_SOURCE_URL_MARKER = "__ISCAN_YTDLP_URL__:";

function isRecord(value: unknown): value is Record<string, unknown> {
	return typeof value === "object" && value !== null && !Array.isArray(value);
}

function normalizeRequiredString(value: unknown, label: string): string {
	if (typeof value !== "string") {
		throw new Error(`${label} must be a string.`);
	}

	const normalized = value.trim();
	if (normalized.length === 0) {
		throw new Error(`${label} must be a non-empty string.`);
	}

	return normalized;
}

function normalizeOptionalString(value: unknown, label: string): string | undefined {
	if (value === undefined || value === null || value === "") {
		return undefined;
	}

	return normalizeRequiredString(value, label);
}

function normalizeBoolean(value: unknown, label: string): boolean | undefined {
	if (value === undefined || value === null || value === "") {
		return undefined;
	}

	if (typeof value !== "boolean") {
		throw new Error(`${label} must be a boolean.`);
	}

	return value;
}

function normalizePositiveInteger(value: unknown, label: string): number | undefined {
	if (value === undefined || value === null || value === "") {
		return undefined;
	}

	const numericValue = typeof value === "number" ? value : Number(value);
	if (!Number.isInteger(numericValue) || numericValue <= 0) {
		throw new Error(`${label} must be a positive integer.`);
	}

	return numericValue;
}

function normalizeOptionalStringArray(value: unknown, label: string): string[] | undefined {
	if (value === undefined || value === null || value === "") {
		return undefined;
	}

	const values = Array.isArray(value) ? value : [value];
	const normalizedValues = values.map((entry, index) => normalizeRequiredString(entry, `${label}[${index}]`));
	return normalizedValues.length > 0 ? normalizedValues : undefined;
}

function createRootCommand(argv: readonly string[]): BpkgTranspiledCommand {
	return {
		argv: [...argv],
		createdAt: Date.now(),
		cwd: "/root",
	};
}

function resolveHostPath(value: unknown, label: string): string {
	return path.resolve(process.cwd(), normalizeRequiredString(value, label));
}

function countAndNormalizeCookieJar(cookieJarText: string): { cookieCount: number; normalizedText: string } {
	const cookieLines: string[] = [];

	for (const rawLine of cookieJarText.split(/\r?\n/u)) {
		const trimmedLine = rawLine.trim();
		if (trimmedLine.length === 0) {
			continue;
		}

		if (trimmedLine.startsWith("#") && !trimmedLine.startsWith("#HttpOnly_")) {
			continue;
		}

		const segments = trimmedLine.split("\t");
		if (segments.length !== 7) {
			throw new Error("yt-dlp cookies file must be a Netscape cookie jar with 7 tab-separated columns.");
		}

		cookieLines.push(trimmedLine);
	}

	if (cookieLines.length === 0) {
		throw new Error("yt-dlp cookies file must contain at least one cookie entry.");
	}

	return {
		cookieCount: cookieLines.length,
		normalizedText: `# Netscape HTTP Cookie File\n# This file was generated or normalized by iscan.\n${cookieLines.join("\n")}\n`,
	};
}

function sanitizeNetscapeField(value: string): string {
	return value.replace(/[\t\r\n]+/gu, " ");
}

function serializeCookiesToNetscape(cookies: readonly CloakProfileCookie[]): string {
	const lines = [
		"# Netscape HTTP Cookie File",
		"# This file was generated by iscan from a CloakBrowser profile.",
	];

	for (const cookie of cookies) {
		const domainPrefix = cookie.httpOnly ? "#HttpOnly_" : "";
		const domainValue = cookie.domain.startsWith(domainPrefix)
			? cookie.domain
			: `${domainPrefix}${cookie.domain}`;
		const effectiveDomain = domainValue.replace(/^#HttpOnly_/u, "");
		const includeSubdomains = effectiveDomain.startsWith(".") ? "TRUE" : "FALSE";
		const expiry = Number.isFinite(cookie.expires) && cookie.expires > 0 ? Math.floor(cookie.expires) : 0;
		lines.push([
			sanitizeNetscapeField(domainValue),
			includeSubdomains,
			sanitizeNetscapeField(cookie.path || "/"),
			cookie.secure ? "TRUE" : "FALSE",
			String(expiry),
			sanitizeNetscapeField(cookie.name),
			sanitizeNetscapeField(cookie.value),
		].join("\t"));
	}

	return `${lines.join("\n")}\n`;
}

function normalizeDownloadOutputDirectory(value: unknown): string {
	return normalizeOptionalString(value, "yt-dlp outputDir") ?? YTDLP_DEFAULT_OUTPUT_DIR;
}

function normalizeDownloadOutputTemplate(value: unknown): string {
	const normalized = normalizeOptionalString(value, "yt-dlp outputTemplate") ?? YTDLP_DEFAULT_OUTPUT_TEMPLATE;
	return normalized.replace(/^~\//u, "/root/");
}

function readOptionalRecordString(record: Record<string, unknown>, key: string): string | undefined {
	const value = record[key];
	return typeof value === "string" && value.trim().length > 0 ? value.trim() : undefined;
}

function readOptionalRecordNumber(record: Record<string, unknown>, key: string): number | undefined {
	const value = record[key];
	return typeof value === "number" && Number.isFinite(value) ? value : undefined;
}

function readOptionalRecordBoolean(record: Record<string, unknown>, key: string): boolean | undefined {
	const value = record[key];
	return typeof value === "boolean" ? value : undefined;
}

function readOptionalRecordStringArray(record: Record<string, unknown>, key: string): string[] | undefined {
	const value = record[key];
	if (!Array.isArray(value)) {
		return undefined;
	}

	const normalized = value
		.filter((entry): entry is string => typeof entry === "string")
		.map((entry) => entry.trim())
		.filter(Boolean);
	return normalized.length > 0 ? normalized : undefined;
}

function readOptionalRecordKeys(record: Record<string, unknown>, key: string): string[] | undefined {
	const value = record[key];
	if (!isRecord(value)) {
		return undefined;
	}

	const keys = Object.keys(value).filter(Boolean);
	return keys.length > 0 ? keys : undefined;
}

function parseYtdlpJsonPayload(stdout: string): Record<string, unknown> {
	let parsed: unknown;
	try {
		parsed = JSON.parse(stdout);
	} catch (error) {
		const detail = error instanceof Error ? error.message : String(error);
		throw new Error(`yt-dlp JSON output could not be parsed: ${detail}`);
	}

	if (!isRecord(parsed)) {
		throw new Error("yt-dlp JSON output must be an object.");
	}

	return parsed;
}

function extractYtdlpEntries(payload: Record<string, unknown>): Record<string, unknown>[] {
	const entriesValue = payload.entries;
	if (Array.isArray(entriesValue)) {
		const entries = entriesValue.filter(isRecord);
		if (entries.length > 0) {
			return entries;
		}
	}

	return [payload];
}

function summarizeYtdlpInfoEntry(entry: Record<string, unknown>): Record<string, unknown> {
	const formats = Array.isArray(entry.formats) ? entry.formats.filter(isRecord) : [];
	return {
		...(readOptionalRecordString(entry, "id") ? { id: readOptionalRecordString(entry, "id") } : {}),
		...(readOptionalRecordString(entry, "title") ? { title: readOptionalRecordString(entry, "title") } : {}),
		...(readOptionalRecordString(entry, "fulltitle") ? { fullTitle: readOptionalRecordString(entry, "fulltitle") } : {}),
		...(readOptionalRecordString(entry, "extractor") ? { extractor: readOptionalRecordString(entry, "extractor") } : {}),
		...(readOptionalRecordString(entry, "extractor_key") ? { extractorKey: readOptionalRecordString(entry, "extractor_key") } : {}),
		...(readOptionalRecordString(entry, "webpage_url") ? { webpageUrl: readOptionalRecordString(entry, "webpage_url") } : {}),
		...(readOptionalRecordString(entry, "original_url") ? { originalUrl: readOptionalRecordString(entry, "original_url") } : {}),
		...(readOptionalRecordString(entry, "description") ? { description: readOptionalRecordString(entry, "description") } : {}),
		...(readOptionalRecordString(entry, "uploader") ? { uploader: readOptionalRecordString(entry, "uploader") } : {}),
		...(readOptionalRecordString(entry, "uploader_id") ? { uploaderId: readOptionalRecordString(entry, "uploader_id") } : {}),
		...(readOptionalRecordString(entry, "channel") ? { channel: readOptionalRecordString(entry, "channel") } : {}),
		...(readOptionalRecordString(entry, "channel_id") ? { channelId: readOptionalRecordString(entry, "channel_id") } : {}),
		...(readOptionalRecordString(entry, "thumbnail") ? { thumbnail: readOptionalRecordString(entry, "thumbnail") } : {}),
		...(readOptionalRecordString(entry, "availability") ? { availability: readOptionalRecordString(entry, "availability") } : {}),
		...(readOptionalRecordString(entry, "live_status") ? { liveStatus: readOptionalRecordString(entry, "live_status") } : {}),
		...(readOptionalRecordString(entry, "language") ? { language: readOptionalRecordString(entry, "language") } : {}),
		...(readOptionalRecordString(entry, "ext") ? { ext: readOptionalRecordString(entry, "ext") } : {}),
		...(readOptionalRecordString(entry, "format_id") ? { formatId: readOptionalRecordString(entry, "format_id") } : {}),
		...(readOptionalRecordString(entry, "format") ? { format: readOptionalRecordString(entry, "format") } : {}),
		...(readOptionalRecordString(entry, "protocol") ? { protocol: readOptionalRecordString(entry, "protocol") } : {}),
		...(readOptionalRecordNumber(entry, "duration") !== undefined ? { durationSeconds: readOptionalRecordNumber(entry, "duration") } : {}),
		...(readOptionalRecordNumber(entry, "view_count") !== undefined ? { viewCount: readOptionalRecordNumber(entry, "view_count") } : {}),
		...(readOptionalRecordNumber(entry, "like_count") !== undefined ? { likeCount: readOptionalRecordNumber(entry, "like_count") } : {}),
		...(readOptionalRecordNumber(entry, "comment_count") !== undefined ? { commentCount: readOptionalRecordNumber(entry, "comment_count") } : {}),
		...(readOptionalRecordNumber(entry, "timestamp") !== undefined ? { timestamp: readOptionalRecordNumber(entry, "timestamp") } : {}),
		...(readOptionalRecordBoolean(entry, "is_live") !== undefined ? { isLive: readOptionalRecordBoolean(entry, "is_live") } : {}),
		...(readOptionalRecordBoolean(entry, "was_live") !== undefined ? { wasLive: readOptionalRecordBoolean(entry, "was_live") } : {}),
		...(readOptionalRecordStringArray(entry, "tags") ? { tags: readOptionalRecordStringArray(entry, "tags") } : {}),
		...(readOptionalRecordStringArray(entry, "categories") ? { categories: readOptionalRecordStringArray(entry, "categories") } : {}),
		...(readOptionalRecordKeys(entry, "subtitles") ? { subtitleLanguages: readOptionalRecordKeys(entry, "subtitles") } : {}),
		...(readOptionalRecordKeys(entry, "automatic_captions") ? { automaticCaptionLanguages: readOptionalRecordKeys(entry, "automatic_captions") } : {}),
		formatCount: formats.length,
		...(Array.isArray(entry.thumbnails) ? { thumbnailCount: entry.thumbnails.length } : {}),
	};
}

function summarizeYtdlpFormat(format: Record<string, unknown>): Record<string, unknown> {
	return {
		...(readOptionalRecordString(format, "format_id") ? { formatId: readOptionalRecordString(format, "format_id") } : {}),
		...(readOptionalRecordString(format, "format") ? { format: readOptionalRecordString(format, "format") } : {}),
		...(readOptionalRecordString(format, "format_note") ? { formatNote: readOptionalRecordString(format, "format_note") } : {}),
		...(readOptionalRecordString(format, "ext") ? { ext: readOptionalRecordString(format, "ext") } : {}),
		...(readOptionalRecordString(format, "resolution") ? { resolution: readOptionalRecordString(format, "resolution") } : {}),
		...(readOptionalRecordString(format, "dynamic_range") ? { dynamicRange: readOptionalRecordString(format, "dynamic_range") } : {}),
		...(readOptionalRecordString(format, "protocol") ? { protocol: readOptionalRecordString(format, "protocol") } : {}),
		...(readOptionalRecordString(format, "vcodec") ? { vcodec: readOptionalRecordString(format, "vcodec") } : {}),
		...(readOptionalRecordString(format, "acodec") ? { acodec: readOptionalRecordString(format, "acodec") } : {}),
		...(readOptionalRecordString(format, "video_ext") ? { videoExt: readOptionalRecordString(format, "video_ext") } : {}),
		...(readOptionalRecordString(format, "audio_ext") ? { audioExt: readOptionalRecordString(format, "audio_ext") } : {}),
		...(readOptionalRecordString(format, "container") ? { container: readOptionalRecordString(format, "container") } : {}),
		...(readOptionalRecordString(format, "language") ? { language: readOptionalRecordString(format, "language") } : {}),
		...(readOptionalRecordNumber(format, "fps") !== undefined ? { fps: readOptionalRecordNumber(format, "fps") } : {}),
		...(readOptionalRecordNumber(format, "tbr") !== undefined ? { tbrKbps: readOptionalRecordNumber(format, "tbr") } : {}),
		...(readOptionalRecordNumber(format, "abr") !== undefined ? { abrKbps: readOptionalRecordNumber(format, "abr") } : {}),
		...(readOptionalRecordNumber(format, "vbr") !== undefined ? { vbrKbps: readOptionalRecordNumber(format, "vbr") } : {}),
		...(readOptionalRecordNumber(format, "filesize") !== undefined ? { fileSizeBytes: readOptionalRecordNumber(format, "filesize") } : {}),
		...(readOptionalRecordNumber(format, "filesize_approx") !== undefined ? { fileSizeApproxBytes: readOptionalRecordNumber(format, "filesize_approx") } : {}),
		...(readOptionalRecordNumber(format, "source_preference") !== undefined ? { sourcePreference: readOptionalRecordNumber(format, "source_preference") } : {}),
	};
}

function buildCookiesUsageMetadata(params: Record<string, unknown>): Record<string, unknown> {
	return {
		...(normalizeOptionalString(params.resolvedCookiesPath, "yt-dlp resolvedCookiesPath")
			? { usedCookiesPath: normalizeRequiredString(params.resolvedCookiesPath, "yt-dlp resolvedCookiesPath") }
			: {}),
		usedPersistentCookies: Boolean(params.usedPersistentCookies),
	};
}

async function prepareResolvedCookiesPath(context: BpkgBindingPrepareContext): Promise<Partial<Record<string, unknown>>> {
	const requestedCookiesPath = normalizeOptionalString(context.params.cookiesPath, "yt-dlp cookiesPath");
	if (requestedCookiesPath) {
		if (!await context.boxFileExists(requestedCookiesPath)) {
			throw new Error(`yt-dlp cookiesPath '${requestedCookiesPath}' does not exist inside the selected box.`);
		}

		return {
			resolvedCookiesPath: requestedCookiesPath,
			usedPersistentCookies: requestedCookiesPath === YTDLP_COOKIE_JAR_PATH,
		};
	}

	if (await context.boxFileExists(YTDLP_COOKIE_JAR_PATH)) {
		return {
			resolvedCookiesPath: YTDLP_COOKIE_JAR_PATH,
			usedPersistentCookies: true,
		};
	}

	return {
		usedPersistentCookies: false,
	};
}

function pushYtdlpExecutionArgs(
	argv: string[],
	params: {
		cookiesPath?: string;
		extraArgs?: string[];
		noPlaylist?: boolean;
		playlistItems?: string;
		proxy?: string;
	},
): void {
	if (params.cookiesPath) {
		argv.push("--cookies", params.cookiesPath);
	}
	if (params.proxy) {
		argv.push("--proxy", params.proxy);
	}
	if (params.noPlaylist) {
		argv.push("--no-playlist");
	}
	if (params.playlistItems) {
		argv.push("--playlist-items", params.playlistItems);
	}
	if (params.extraArgs && params.extraArgs.length > 0) {
		argv.push(...params.extraArgs);
	}
}

function readMarkedValues(text: string, marker: string): string[] {
	return text
		.split(/\r?\n/u)
		.map((line) => line.trim())
		.filter((line) => line.startsWith(marker))
		.map((line) => line.slice(marker.length).trim())
		.filter(Boolean);
}

async function preparePersistentCookieJar(
	context: BpkgBindingPrepareContext,
	cookieJarText: string,
	metadata: Partial<Record<string, unknown>>,
): Promise<Partial<Record<string, unknown>>> {
	const { cookieCount, normalizedText } = countAndNormalizeCookieJar(cookieJarText);
	await context.writeBoxFile(YTDLP_COOKIE_JAR_PATH, normalizedText);
	return {
		cookieJarPath: YTDLP_COOKIE_JAR_PATH,
		importedCookieCount: cookieCount,
		...metadata,
	};
}

const ytdlpDownloadResponseParser: BpkgBindingResponseParser = async (result, context) => {
	const destinationPaths = readMarkedValues(result.stdout, YTDLP_DESTINATION_MARKER);
	const sourceUrls = readMarkedValues(result.stdout, YTDLP_SOURCE_URL_MARKER);
	const downloadCount = Math.max(destinationPaths.length, sourceUrls.length);

	return {
		bindingId: context.bindingId,
		downloads: Array.from({ length: downloadCount }, (_value, index) => ({
			...(destinationPaths[index] ? { destinationPath: destinationPaths[index] } : {}),
			...(sourceUrls[index] ? { sourceUrl: sourceUrls[index] } : {}),
		})),
		kind: "ytdlp-download",
		outputDir: normalizeDownloadOutputDirectory(context.params.outputDir),
		targetUrl: normalizeRequiredString(context.params.url, "yt-dlp url"),
		...buildCookiesUsageMetadata(context.params),
	};
};

const ytdlpInfoResponseParser: BpkgBindingResponseParser = async (result, context) => {
	const payload = parseYtdlpJsonPayload(result.stdout);
	const entries = extractYtdlpEntries(payload);

	return {
		bindingId: context.bindingId,
		entries: entries.map(summarizeYtdlpInfoEntry),
		entryCount: entries.length,
		kind: "ytdlp-info",
		...(readOptionalRecordString(payload, "id") ? { id: readOptionalRecordString(payload, "id") } : {}),
		...(readOptionalRecordString(payload, "title") ? { title: readOptionalRecordString(payload, "title") } : {}),
		...(readOptionalRecordString(payload, "extractor") ? { extractor: readOptionalRecordString(payload, "extractor") } : {}),
		...(readOptionalRecordString(payload, "webpage_url") ? { webpageUrl: readOptionalRecordString(payload, "webpage_url") } : {}),
		targetUrl: normalizeRequiredString(context.params.url, "yt-dlp url"),
		...buildCookiesUsageMetadata(context.params),
	};
};

const ytdlpListFormatsResponseParser: BpkgBindingResponseParser = async (result, context) => {
	const payload = parseYtdlpJsonPayload(result.stdout);
	const entries = extractYtdlpEntries(payload);

	return {
		bindingId: context.bindingId,
		entries: entries.map((entry) => ({
			...(readOptionalRecordString(entry, "id") ? { id: readOptionalRecordString(entry, "id") } : {}),
			...(readOptionalRecordString(entry, "title") ? { title: readOptionalRecordString(entry, "title") } : {}),
			...(readOptionalRecordString(entry, "extractor") ? { extractor: readOptionalRecordString(entry, "extractor") } : {}),
			...(readOptionalRecordString(entry, "webpage_url") ? { webpageUrl: readOptionalRecordString(entry, "webpage_url") } : {}),
			formats: (Array.isArray(entry.formats) ? entry.formats.filter(isRecord) : []).map(summarizeYtdlpFormat),
		})),
		entryCount: entries.length,
		kind: "ytdlp-formats",
		targetUrl: normalizeRequiredString(context.params.url, "yt-dlp url"),
		...buildCookiesUsageMetadata(context.params),
	};
};

const ytdlpImportResponseParser: BpkgBindingResponseParser = async (_result, context) => ({
	bindingId: context.bindingId,
	cookieJarPath: normalizeRequiredString(context.params.cookieJarPath, "yt-dlp cookieJarPath"),
	importedCookieCount: Number(context.params.importedCookieCount ?? 0),
	kind: "ytdlp-cookie-jar",
	...(normalizeOptionalString(context.params.sourcePath, "yt-dlp sourcePath")
		? { sourcePath: normalizeRequiredString(context.params.sourcePath, "yt-dlp sourcePath") }
		: {}),
	...(normalizeOptionalString(context.params.profileId, "yt-dlp profileId")
		? { profileId: normalizeRequiredString(context.params.profileId, "yt-dlp profileId") }
		: {}),
	...(normalizeOptionalStringArray(context.params.domains, "yt-dlp domains")
		? { domains: normalizeOptionalStringArray(context.params.domains, "yt-dlp domains") }
		: {}),
});

export const ytdlpBindings = defineBindings({
	package: "@bpkg/yt-dlp",
	description: "yt-dlp - scripted media downloads with persistent cookie jar support inside bpkg boxes.",
	dependency: {
		pacman: ["yt-dlp", "ffmpeg"],
	},
	id: "ytdlp",
	bindings: {
		download: {
			description: "Download media with yt-dlp into the selected bpkg box.",
			defaultParameterName: "url",
			parameters: {
				url: {
					type: "string",
					description: "Target media or playlist URL.",
					example: "https://www.youtube.com/watch?v=BaW_jenozKc",
					required: true,
				},
				outputDir: {
					type: "string",
					description: "Optional output directory inside the selected box. Defaults to /root/Downloads.",
					example: "/root/Downloads",
				},
				outputTemplate: {
					type: "string",
					description: "Optional yt-dlp output template.",
					example: "%(title)s [%(id)s].%(ext)s",
				},
				proxy: {
					type: "string",
					description: "Optional outbound proxy, for example socks5://user:pass@host:port.",
					example: "socks5://user:pass@host:1080",
				},
				format: {
					type: "string",
					description: "Optional yt-dlp format selector.",
					example: "bv*+ba/b",
				},
				extractAudio: {
					type: "boolean",
					description: "Extract audio after download.",
					example: "true",
				},
				audioFormat: {
					type: "string",
					description: "Optional audio format when extractAudio=true.",
					example: "mp3",
				},
				audioQuality: {
					type: "string",
					description: "Optional audio quality passed to --audio-quality, for example 320K or 0.",
					example: "320K",
				},
				playlistItems: {
					type: "string",
					description: "Optional yt-dlp playlist item selection, for example 1,3-5.",
					example: "1,3-5",
				},
				noPlaylist: {
					type: "boolean",
					description: "Force single-entry extraction with --no-playlist.",
					example: "true",
				},
				writeInfoJson: {
					type: "boolean",
					description: "Write the video metadata JSON next to the download.",
					example: "true",
				},
				writeDescription: {
					type: "boolean",
					description: "Write the extracted description next to the download.",
					example: "true",
				},
				writeComments: {
					type: "boolean",
					description: "Write extracted comments when supported by the site.",
					example: "true",
				},
				writeThumbnail: {
					type: "boolean",
					description: "Write the thumbnail next to the download.",
					example: "true",
				},
				writeSub: {
					type: "boolean",
					description: "Write subtitles when available.",
					example: "true",
				},
				subLangs: {
					type: "string[]",
					description: "Optional subtitle languages, for example en or en.*,ru.",
					example: "en,ru",
				},
				embedMetadata: {
					type: "boolean",
					description: "Embed metadata tags into the downloaded media when supported.",
					example: "true",
				},
				embedThumbnail: {
					type: "boolean",
					description: "Embed the thumbnail into the output file when supported.",
					example: "true",
				},
				embedSubs: {
					type: "boolean",
					description: "Embed downloaded subtitles into the output file when supported.",
					example: "true",
				},
				embedChapters: {
					type: "boolean",
					description: "Embed chapter metadata into the output file when supported.",
					example: "true",
				},
				splitChapters: {
					type: "boolean",
					description: "Split the download into separate files per chapter.",
					example: "true",
				},
				sponsorBlockMark: {
					type: "string[]",
					description: "SponsorBlock categories to mark as chapters, for example sponsor,intro,outro.",
					example: "sponsor,intro,outro",
				},
				sponsorBlockRemove: {
					type: "string[]",
					description: "SponsorBlock categories to remove entirely, for example sponsor,selfpromo.",
					example: "sponsor,selfpromo",
				},
				retries: {
					type: "number",
					description: "Retry count for extraction and download failures.",
					example: "5",
				},
				sleepInterval: {
					type: "number",
					description: "Pause between downloads in seconds.",
					example: "5",
				},
				fragmentRetries: {
					type: "number",
					description: "Retry count for fragment downloads.",
					example: "5",
				},
				concurrentFragments: {
					type: "number",
					description: "Number of fragments to download in parallel.",
					example: "4",
				},
				limitRate: {
					type: "string",
					description: "Optional rate limit such as 2M or 500K.",
					example: "2M",
				},
				mergeOutputFormat: {
					type: "string",
					description: "Preferred output container when merging streams.",
					example: "mp4",
				},
				remuxVideo: {
					type: "string",
					description: "Remux the output to the given container when possible.",
					example: "mp4",
				},
				recodeVideo: {
					type: "string",
					description: "Re-encode the video to the given format when needed.",
					example: "mp4",
				},
				keepVideo: {
					type: "boolean",
					description: "Keep the source video after audio extraction or other post-processing.",
					example: "true",
				},
				noPart: {
					type: "boolean",
					description: "Disable .part files during download.",
					example: "true",
				},
				restrictFilenames: {
					type: "boolean",
					description: "Restrict filenames to ASCII-safe characters.",
					example: "true",
				},
				forceOverwrites: {
					type: "boolean",
					description: "Overwrite existing output files without prompting.",
					example: "true",
				},
				noMtime: {
					type: "boolean",
					description: "Do not use the Last-Modified header to set the file mtime.",
					example: "true",
				},
				cookiesPath: {
					type: "string",
					description: "Optional cookie jar path inside the selected box. Defaults to the imported persistent jar when present.",
					example: "/root/.config/yt-dlp/cookies.txt",
				},
				extraArgs: {
					type: "string[]",
					description: "Optional raw yt-dlp CLI args appended after the generated arguments.",
					example: "--embed-metadata,--newline",
				},
			},
			prepare: prepareResolvedCookiesPath,
			responseParser: ytdlpDownloadResponseParser,
		},
		info: {
			description: "Fetch structured yt-dlp metadata without downloading media.",
			defaultParameterName: "url",
			parameters: {
				url: {
					type: "string",
					description: "Target media or playlist URL.",
					example: "https://www.youtube.com/watch?v=BaW_jenozKc",
					required: true,
				},
				playlistItems: {
					type: "string",
					description: "Optional yt-dlp playlist item selection, for example 1,3-5.",
					example: "1,3-5",
				},
				noPlaylist: {
					type: "boolean",
					description: "Force single-entry extraction with --no-playlist.",
					example: "true",
				},
				flatPlaylist: {
					type: "boolean",
					description: "Use yt-dlp --flat-playlist for faster playlist metadata collection.",
					example: "true",
				},
				cookiesPath: {
					type: "string",
					description: "Optional cookie jar path inside the selected box. Defaults to the imported persistent jar when present.",
					example: "/root/.config/yt-dlp/cookies.txt",
				},
				proxy: {
					type: "string",
					description: "Optional outbound proxy, for example socks5://user:pass@host:port.",
					example: "socks5://user:pass@host:1080",
				},
				extraArgs: {
					type: "string[]",
					description: "Optional raw yt-dlp CLI args appended after the generated arguments.",
					example: "--geo-bypass,--compat-options,no-youtube-unavailable-videos",
				},
			},
			prepare: prepareResolvedCookiesPath,
			responseParser: ytdlpInfoResponseParser,
		},
		listFormats: {
			description: "List structured format variants reported by yt-dlp for the target URL.",
			defaultParameterName: "url",
			parameters: {
				url: {
					type: "string",
					description: "Target media or playlist URL.",
					example: "https://www.youtube.com/watch?v=BaW_jenozKc",
					required: true,
				},
				playlistItems: {
					type: "string",
					description: "Optional yt-dlp playlist item selection, for example 1,3-5.",
					example: "1,3-5",
				},
				noPlaylist: {
					type: "boolean",
					description: "Force single-entry extraction with --no-playlist.",
					example: "true",
				},
				cookiesPath: {
					type: "string",
					description: "Optional cookie jar path inside the selected box. Defaults to the imported persistent jar when present.",
					example: "/root/.config/yt-dlp/cookies.txt",
				},
				proxy: {
					type: "string",
					description: "Optional outbound proxy, for example socks5://user:pass@host:port.",
					example: "socks5://user:pass@host:1080",
				},
				extraArgs: {
					type: "string[]",
					description: "Optional raw yt-dlp CLI args appended after the generated arguments.",
					example: "--check-formats,--allow-dynamic-mpd",
				},
			},
			prepare: prepareResolvedCookiesPath,
			responseParser: ytdlpListFormatsResponseParser,
		},
		importCookies: {
			description: "Import a host Netscape cookies.txt file into the selected box as the default yt-dlp cookie jar.",
			defaultParameterName: "path",
			parameters: {
				path: {
					type: "string",
					description: "Host path to a Netscape cookies.txt file.",
					example: "/home/john/cookies.txt",
					required: true,
				},
			},
			prepare: async (context) => {
				const sourcePath = resolveHostPath(context.params.path, "yt-dlp cookies path");
				const cookieJarText = await fs.readFile(sourcePath, "utf8");
				return await preparePersistentCookieJar(context, cookieJarText, {
					sourcePath,
				});
			},
			responseParser: ytdlpImportResponseParser,
		},
		importCookiesFromCloakBrowser: {
			description: "Export cookies from a CloakBrowser profile into the selected box as the default yt-dlp cookie jar.",
			defaultParameterName: "profileId",
			parameters: {
				profileId: {
					type: "string",
					description: "CloakBrowser profile id or unique profile name.",
					example: "profile-65372bfe",
					required: true,
				},
				domains: {
					type: "string[]",
					description: "Optional cookie domain filters, for example youtube.com,google.com.",
					example: "youtube.com",
				},
			},
			prepare: async (context) => {
				const profileId = normalizeRequiredString(context.params.profileId, "yt-dlp profileId");
				const domains = normalizeOptionalStringArray(context.params.domains, "yt-dlp domains");
				const cloakKit = await context.runtime.ensureKit(CLOAK_KIT_ID, () => new CloakKit(), {
					reason: `bpkg:ytdlp/${context.bindingId}`,
				}) as CloakKit;
				const cookies = await cloakKit.getProfileCookies(profileId, {
					autoLaunch: true,
					domains,
				});

				if (cookies.length === 0) {
					throw new Error(`CloakBrowser profile '${profileId}' did not yield any cookies for yt-dlp import.`);
				}

				return await preparePersistentCookieJar(context, serializeCookiesToNetscape(cookies), {
					domains,
					profileId,
				});
			},
			responseParser: ytdlpImportResponseParser,
		},
	},
	transformers: {
		async download(params) {
			const targetUrl = normalizeRequiredString(params.url, "yt-dlp url");
			const outputDirectory = normalizeDownloadOutputDirectory(params.outputDir);
			const outputTemplate = normalizeDownloadOutputTemplate(params.outputTemplate);
			const proxy = normalizeOptionalString(params.proxy, "yt-dlp proxy");
			const format = normalizeOptionalString(params.format, "yt-dlp format");
			const extractAudio = normalizeBoolean(params.extractAudio, "yt-dlp extractAudio") ?? false;
			const audioFormat = normalizeOptionalString(params.audioFormat, "yt-dlp audioFormat");
			const audioQuality = normalizeOptionalString(params.audioQuality, "yt-dlp audioQuality");
			const playlistItems = normalizeOptionalString(params.playlistItems, "yt-dlp playlistItems");
			const noPlaylist = normalizeBoolean(params.noPlaylist, "yt-dlp noPlaylist") ?? false;
			const writeInfoJson = normalizeBoolean(params.writeInfoJson, "yt-dlp writeInfoJson") ?? false;
			const writeDescription = normalizeBoolean(params.writeDescription, "yt-dlp writeDescription") ?? false;
			const writeComments = normalizeBoolean(params.writeComments, "yt-dlp writeComments") ?? false;
			const writeThumbnail = normalizeBoolean(params.writeThumbnail, "yt-dlp writeThumbnail") ?? false;
			const writeSub = normalizeBoolean(params.writeSub, "yt-dlp writeSub") ?? false;
			const subLangs = normalizeOptionalStringArray(params.subLangs, "yt-dlp subLangs") ?? [];
			const embedMetadata = normalizeBoolean(params.embedMetadata, "yt-dlp embedMetadata") ?? false;
			const embedThumbnail = normalizeBoolean(params.embedThumbnail, "yt-dlp embedThumbnail") ?? false;
			const embedSubs = normalizeBoolean(params.embedSubs, "yt-dlp embedSubs") ?? false;
			const embedChapters = normalizeBoolean(params.embedChapters, "yt-dlp embedChapters") ?? false;
			const splitChapters = normalizeBoolean(params.splitChapters, "yt-dlp splitChapters") ?? false;
			const sponsorBlockMark = normalizeOptionalStringArray(params.sponsorBlockMark, "yt-dlp sponsorBlockMark") ?? [];
			const sponsorBlockRemove = normalizeOptionalStringArray(params.sponsorBlockRemove, "yt-dlp sponsorBlockRemove") ?? [];
			const retries = normalizePositiveInteger(params.retries, "yt-dlp retries");
			const sleepInterval = normalizePositiveInteger(params.sleepInterval, "yt-dlp sleepInterval");
			const fragmentRetries = normalizePositiveInteger(params.fragmentRetries, "yt-dlp fragmentRetries");
			const concurrentFragments = normalizePositiveInteger(params.concurrentFragments, "yt-dlp concurrentFragments");
			const limitRate = normalizeOptionalString(params.limitRate, "yt-dlp limitRate");
			const mergeOutputFormat = normalizeOptionalString(params.mergeOutputFormat, "yt-dlp mergeOutputFormat");
			const remuxVideo = normalizeOptionalString(params.remuxVideo, "yt-dlp remuxVideo");
			const recodeVideo = normalizeOptionalString(params.recodeVideo, "yt-dlp recodeVideo");
			const keepVideo = normalizeBoolean(params.keepVideo, "yt-dlp keepVideo") ?? false;
			const noPart = normalizeBoolean(params.noPart, "yt-dlp noPart") ?? false;
			const restrictFilenames = normalizeBoolean(params.restrictFilenames, "yt-dlp restrictFilenames") ?? false;
			const forceOverwrites = normalizeBoolean(params.forceOverwrites, "yt-dlp forceOverwrites") ?? false;
			const noMtime = normalizeBoolean(params.noMtime, "yt-dlp noMtime") ?? false;
			const cookiesPath = normalizeOptionalString(params.resolvedCookiesPath, "yt-dlp resolvedCookiesPath");
			const extraArgs = normalizeOptionalStringArray(params.extraArgs, "yt-dlp extraArgs") ?? [];

			if (audioFormat && !extractAudio) {
				throw new Error("yt-dlp audioFormat requires extractAudio=true.");
			}
			if (audioQuality && !extractAudio) {
				throw new Error("yt-dlp audioQuality requires extractAudio=true.");
			}

			const argv = [
				"yt-dlp",
				"--paths",
				outputDirectory,
				"-o",
				outputTemplate,
				"--print",
				`before_dl:${YTDLP_SOURCE_URL_MARKER}%(webpage_url)s`,
				"--print",
				`after_move:${YTDLP_DESTINATION_MARKER}%(filepath)s`,
			];

			pushYtdlpExecutionArgs(argv, { cookiesPath, extraArgs: [], noPlaylist, playlistItems, proxy });
			if (format) {
				argv.push("-f", format);
			}
			if (retries !== undefined) {
				argv.push("--retries", String(retries));
			}
			if (fragmentRetries !== undefined) {
				argv.push("--fragment-retries", String(fragmentRetries));
			}
			if (concurrentFragments !== undefined) {
				argv.push("--concurrent-fragments", String(concurrentFragments));
			}
			if (limitRate) {
				argv.push("--limit-rate", limitRate);
			}
			if (forceOverwrites) {
				argv.push("--force-overwrites");
			}
			if (noPart) {
				argv.push("--no-part");
			}
			if (restrictFilenames) {
				argv.push("--restrict-filenames");
			}
			if (noMtime) {
				argv.push("--no-mtime");
			}
			if (extractAudio) {
				argv.push("-x");
			}
			if (audioFormat) {
				argv.push("--audio-format", audioFormat);
			}
			if (audioQuality) {
				argv.push("--audio-quality", audioQuality);
			}
			if (writeInfoJson) {
				argv.push("--write-info-json");
			}
			if (writeDescription) {
				argv.push("--write-description");
			}
			if (writeComments) {
				argv.push("--write-comments");
			}
			if (writeThumbnail) {
				argv.push("--write-thumbnail");
			}
			if (writeSub || subLangs.length > 0) {
				argv.push("--write-subs");
			}
			if (subLangs.length > 0) {
				argv.push("--sub-langs", subLangs.join(","));
			}
			if (embedMetadata) {
				argv.push("--embed-metadata");
			}
			if (embedThumbnail) {
				argv.push("--embed-thumbnail");
			}
			if (embedSubs) {
				argv.push("--embed-subs");
			}
			if (embedChapters) {
				argv.push("--embed-chapters");
			}
			if (splitChapters) {
				argv.push("--split-chapters");
			}
			if (sponsorBlockMark.length > 0) {
				argv.push("--sponsorblock-mark", sponsorBlockMark.join(","));
			}
			if (sponsorBlockRemove.length > 0) {
				argv.push("--sponsorblock-remove", sponsorBlockRemove.join(","));
			}
			if (sleepInterval !== undefined) {
				argv.push("--sleep-interval", String(sleepInterval));
			}
			if (mergeOutputFormat) {
				argv.push("--merge-output-format", mergeOutputFormat);
			}
			if (remuxVideo) {
				argv.push("--remux-video", remuxVideo);
			}
			if (recodeVideo) {
				argv.push("--recode-video", recodeVideo);
			}
			if (keepVideo) {
				argv.push("--keep-video");
			}
			argv.push(...extraArgs, targetUrl);
			return createRootCommand(argv);
		},
		async info(params) {
			const targetUrl = normalizeRequiredString(params.url, "yt-dlp url");
			const playlistItems = normalizeOptionalString(params.playlistItems, "yt-dlp playlistItems");
			const noPlaylist = normalizeBoolean(params.noPlaylist, "yt-dlp noPlaylist") ?? false;
			const flatPlaylist = normalizeBoolean(params.flatPlaylist, "yt-dlp flatPlaylist") ?? false;
			const cookiesPath = normalizeOptionalString(params.resolvedCookiesPath, "yt-dlp resolvedCookiesPath");
			const proxy = normalizeOptionalString(params.proxy, "yt-dlp proxy");
			const extraArgs = normalizeOptionalStringArray(params.extraArgs, "yt-dlp extraArgs") ?? [];

			const argv = ["yt-dlp", "-J"];
			pushYtdlpExecutionArgs(argv, { cookiesPath, extraArgs, noPlaylist, playlistItems, proxy });
			if (flatPlaylist) {
				argv.push("--flat-playlist");
			}
			argv.push(targetUrl);
			return createRootCommand(argv);
		},
		async listFormats(params) {
			const targetUrl = normalizeRequiredString(params.url, "yt-dlp url");
			const playlistItems = normalizeOptionalString(params.playlistItems, "yt-dlp playlistItems");
			const noPlaylist = normalizeBoolean(params.noPlaylist, "yt-dlp noPlaylist") ?? false;
			const cookiesPath = normalizeOptionalString(params.resolvedCookiesPath, "yt-dlp resolvedCookiesPath");
			const proxy = normalizeOptionalString(params.proxy, "yt-dlp proxy");
			const extraArgs = normalizeOptionalStringArray(params.extraArgs, "yt-dlp extraArgs") ?? [];

			const argv = ["yt-dlp", "-J"];
			pushYtdlpExecutionArgs(argv, { cookiesPath, extraArgs, noPlaylist, playlistItems, proxy });
			argv.push(targetUrl);
			return createRootCommand(argv);
		},
		async importCookies() {
			return createRootCommand(["test", "-s", YTDLP_COOKIE_JAR_PATH]);
		},
		async importCookiesFromCloakBrowser() {
			return createRootCommand(["test", "-s", YTDLP_COOKIE_JAR_PATH]);
		},
	},
});

export default ytdlpBindings;