import type { ModuleDefinition } from "./module";
import { auditViteSpaModule, auditViteSourcemapsModule } from "./audit";
import { aircrackDslModule } from "./aircrack";
import {
	atoolDslModule,
	bpkgCreateModule,
	bpkgGeneratedPackageModules,
	bpkgGetModule,
	bpkgInstallModule,
	bpkgListModule,
	bpkgPackagesModule,
	bpkgPrivilegeGetModule,
	bpkgPrivilegeSetModule,
	bpkgSelectModule,
	bpkgUseExecModule,
	ytdlpDslModule,
} from "./bpkg";
import { ftpDslModule } from "./ftp";
import { hwDslModule } from "./hw";
import { nmapParseXmlModule, nmapReadXmlModule } from "./nmap";
import { coreModulesModule, coreTaskManagerModule } from "./core";
import {
	dockerBuildModule,
	dockerCdModule,
	dockerComposeDownModule,
	dockerComposeLogsModule,
	dockerComposePsModule,
	dockerComposePullModule,
	dockerComposeRestartModule,
	dockerComposeUpModule,
	dockerExecModule,
	dockerImagesModule,
	dockerInspectModule,
	dockerPsModule,
	dockerPullModule,
	dockerPwdModule,
	dockerRunModule,
} from "./docker";
import {
	gitAddModule,
	gitBranchModule,
	gitBranchCreateModule,
	gitBranchDeleteModule,
	gitCdModule,
	gitCheckoutModule,
	gitCloneModule,
	gitCommitModule,
	gitDiffModule,
	gitFetchModule,
	gitInitModule,
	gitLogModule,
	gitMergeModule,
	gitPullModule,
	gitPwdModule,
	gitPushModule,
	gitRebaseModule,
	gitRestoreModule,
	gitStatusModule,
	gitSwitchModule,
	gitTagCreateModule,
	gitTagDeleteModule,
	gitTagModule,
} from "./git";
import {
	pacmanCleanModule,
	pacmanConfigGetModule,
	pacmanConfigSetModule,
	pacmanDatabaseCheckModule,
	pacmanDatabaseCleanModule,
	pacmanDatabaseMarkDepsModule,
	pacmanInfoModule,
	pacmanInstallModule,
	pacmanListModule,
	pacmanQueryAllModule,
	pacmanQueryFindFileModule,
	pacmanQueryInfoModule,
	pacmanQueryOrphansModule,
	pacmanRemoveModule,
	pacmanRemovePurgeModule,
	pacmanRemoveRecursiveModule,
	pacmanRemoveSoftModule,
	pacmanSearchModule,
	pacmanSyncFullUpgradeModule,
	pacmanSyncInstallModule,
	pacmanSyncModule,
	pacmanSyncSearchModule,
	pacmanSyncUpdateModule,
} from "./pacman";
import {
	paruAurDownloadModule,
	paruAurInspectModule,
	paruAurSearchModule,
	paruConfigGetModule,
	paruConfigSetModule,
	paruInstallModule,
	paruRemoveModule,
	paruUpdateAurOnlyModule,
	paruUpdateSystemModule,
} from "./paru";
import {
	apacheFilesModule,
	cloudflareRadarDomainsPullModule,
	cloudflareRadarDomainsSearchModule,
	discoveryHunterNowApacheIndexModule,
	domainLookupModule,
	zoomEyePullModule,
	zoomEyeSelectModule,
} from "./discovery";
import { gamesTicTacToeModule, gamesHangmanModule } from "./games";
import { aiChatModule, aiConnectModule, aiListModule, axiosModule, elasticSearchConnectModule, elasticSearchExploreModule, elasticSearchSearchModule, kitsManagerModule, microlinkUaListModule, microlinkUaRefreshModule, ollamaConnectModule, qemuConnectModule, qemuDeleteModule, qemuEnvironmentModule, qemuGetModule, qemuListModule, qemuManagerModule, qemuPreviewModule, qemuSaveModule, cloakManagerModule, proxyDeleteModule, proxyImportModule, proxyListModule, proxyManagerModule, proxyReplaceModule, proxySaveModule, proxyTestModule } from "./kits";
import { sqlModule } from "./sql";

export const registeredModules: readonly ModuleDefinition<unknown, unknown, object>[] = [
	coreModulesModule,
	coreTaskManagerModule,
	bpkgListModule,
	bpkgPackagesModule,
	bpkgGetModule,
	bpkgCreateModule,
	bpkgPrivilegeGetModule,
	bpkgPrivilegeSetModule,
	bpkgSelectModule,
	bpkgInstallModule,
	bpkgUseExecModule,
	atoolDslModule,
	ytdlpDslModule,
	aircrackDslModule,
	ftpDslModule,
	hwDslModule,
	nmapParseXmlModule,
	nmapReadXmlModule,
	...bpkgGeneratedPackageModules,
	dockerPwdModule,
	dockerCdModule,
	dockerPullModule,
	dockerPsModule,
	dockerImagesModule,
	dockerInspectModule,
	dockerBuildModule,
	dockerRunModule,
	dockerExecModule,
	gitPwdModule,
	gitCdModule,
	gitCloneModule,
	gitInitModule,
	gitStatusModule,
	gitBranchModule,
	gitBranchCreateModule,
	gitBranchDeleteModule,
	gitLogModule,
	gitDiffModule,
	gitAddModule,
	gitCommitModule,
	gitRestoreModule,
	gitFetchModule,
	gitPullModule,
	gitPushModule,
	gitCheckoutModule,
	gitSwitchModule,
	gitMergeModule,
	gitRebaseModule,
	gitTagModule,
	gitTagCreateModule,
	gitTagDeleteModule,
	pacmanConfigGetModule,
	pacmanConfigSetModule,
	pacmanInstallModule,
	pacmanListModule,
	pacmanSearchModule,
	pacmanInfoModule,
	pacmanSyncModule,
	pacmanRemoveModule,
	pacmanCleanModule,
	pacmanSyncInstallModule,
	pacmanSyncUpdateModule,
	pacmanSyncFullUpgradeModule,
	pacmanSyncSearchModule,
	pacmanQueryAllModule,
	pacmanQueryInfoModule,
	pacmanQueryFindFileModule,
	pacmanQueryOrphansModule,
	pacmanRemoveSoftModule,
	pacmanRemoveRecursiveModule,
	pacmanRemovePurgeModule,
	pacmanDatabaseMarkDepsModule,
	pacmanDatabaseCheckModule,
	pacmanDatabaseCleanModule,
	paruConfigGetModule,
	paruConfigSetModule,
	paruInstallModule,
	paruRemoveModule,
	paruUpdateSystemModule,
	paruUpdateAurOnlyModule,
	paruAurSearchModule,
	paruAurInspectModule,
	paruAurDownloadModule,
	dockerComposePullModule,
	dockerComposeUpModule,
	dockerComposeDownModule,
	dockerComposePsModule,
	dockerComposeRestartModule,
	dockerComposeLogsModule,
	auditViteSpaModule,
	auditViteSourcemapsModule,
	apacheFilesModule,
	cloudflareRadarDomainsPullModule,
	cloudflareRadarDomainsSearchModule,
	domainLookupModule,
	zoomEyePullModule,
	zoomEyeSelectModule,
	gamesTicTacToeModule,
	gamesHangmanModule,
	kitsManagerModule,
	aiConnectModule,
	aiListModule,
	aiChatModule,
	cloakManagerModule,
	proxyImportModule,
	proxyReplaceModule,
	proxyListModule,
	microlinkUaListModule,
	microlinkUaRefreshModule,
	proxySaveModule,
	proxyDeleteModule,
	proxyTestModule,
	proxyManagerModule,
	elasticSearchConnectModule,
	elasticSearchExploreModule,
	elasticSearchSearchModule,
	ollamaConnectModule,
	qemuConnectModule,
	qemuListModule,
	qemuGetModule,
	qemuPreviewModule,
	qemuEnvironmentModule,
	qemuSaveModule,
	qemuDeleteModule,
	qemuManagerModule,
	discoveryHunterNowApacheIndexModule,
	axiosModule,
	sqlModule,
	];