export const workbookTheme = {
  palette: {
    canvas: "#121212",
    rail: "#0d0d0d",
    textCanvas: "#f5f5f5",
    textPrimary: "#ececf2",
    textSecondary: "#8e8e97",
    textMuted: "#8d8d96",
    textLabel: "#7d7d86",
    textLabelSoft: "#7e7e86",
    textTertiary: "#74747d",
    textPlaceholder: "#5f5f69",
    textPlaceholderSoft: "#6d6d76",
    textBody: "#d8d8df",
    textBodySoft: "#dfe1e8",
    textBodyMuted: "#c2c4cc",
    textBodyDim: "#9ea1ab",
    textTag: "#cfd0d8",
    textTableHeader: "#d4d5dc",
    textQuiet: "#6f737d",
    textControl: "#72727a",
  },
  surface: {
    canvas: "bg-[#121212]",
    rail: "bg-[#0d0d0d]",
    panel: "bg-black/20",
    panelMuted: "bg-black/15",
    panelStrong: "bg-black/25",
    overlay: "bg-white/[0.03]",
    softAccent: "bg-white/[0.05]",
  },
  border: {
    default: "border-white/[0.06]",
    subtle: "border-white/[0.05]",
  },
  line: {
    default: "bg-white/[0.06]",
  },
  text: {
    canvas: "text-[#f5f5f5]",
    primary: "text-[#ececf2]",
    secondary: "text-[#8e8e97]",
    muted: "text-[#8d8d96]",
    label: "text-[#7d7d86]",
    labelSoft: "text-[#7e7e86]",
    tertiary: "text-[#74747d]",
    placeholder: "placeholder:text-[#5f5f69]",
    placeholderSoft: "placeholder:text-[#6d6d76]",
    body: "text-[#d8d8df]",
    bodySoft: "text-[#dfe1e8]",
    bodyMuted: "text-[#c2c4cc]",
    bodyDim: "text-[#9ea1ab]",
    tag: "text-[#cfd0d8]",
    tableHeader: "text-[#d4d5dc]",
    quiet: "text-[#6f737d]",
    control: "text-[#72727a]",
  },
  interaction: {
    hover: "hover:bg-white/[0.04]",
    hoverStrong: "hover:bg-white/[0.08]",
    active: "bg-white/[0.08]",
    button: "bg-white/[0.08] hover:bg-white/[0.12]",
    buttonSubtle: "bg-white/[0.06] hover:bg-white/[0.08]",
    panelHoverStrong: "hover:bg-black/35",
  },
} as const;

export default workbookTheme;